// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-QprL7VkdoPr4QBmXmJ08OWxp-FblIGc',
    appId: '1:384062554696:web:hexbuzz',
    messagingSenderId: '384062554696',
    projectId: 'hexbuzz-game',
    authDomain: 'hexbuzz-game.firebaseapp.com',
    storageBucket: 'hexbuzz-game.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-QprL7VkdoPr4QBmXmJ08OWxp-FblIGc',
    appId: '1:384062554696:android:hexbuzz',
    messagingSenderId: '384062554696',
    projectId: 'hexbuzz-game',
    storageBucket: 'hexbuzz-game.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-QprL7VkdoPr4QBmXmJ08OWxp-FblIGc',
    appId: '1:384062554696:ios:hexbuzz',
    messagingSenderId: '384062554696',
    projectId: 'hexbuzz-game',
    storageBucket: 'hexbuzz-game.appspot.com',
    iosBundleId: 'com.hexbuzz.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-QprL7VkdoPr4QBmXmJ08OWxp-FblIGc',
    appId: '1:384062554696:macos:hexbuzz',
    messagingSenderId: '384062554696',
    projectId: 'hexbuzz-game',
    storageBucket: 'hexbuzz-game.appspot.com',
    iosBundleId: 'com.hexbuzz.app.macos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-QprL7VkdoPr4QBmXmJ08OWxp-FblIGc',
    appId: '1:384062554696:windows:hexbuzz',
    messagingSenderId: '384062554696',
    projectId: 'hexbuzz-game',
    authDomain: 'hexbuzz-game.firebaseapp.com',
    storageBucket: 'hexbuzz-game.appspot.com',
  );
}
